### PR TITLE
cherry-pick over the groups fix

### LINKED ISSUE #12: When logging in with fin, the wrong groups are set and the logged in user is a member of `root`
What the title says. This is a regression caused by e5dd3dfb654c9bc2f9d38b6716b6adf3517b3eea .

 PR #11.

### PR DESCRIPTION
**Pull request by taigrr**
Also, normalize the indentation of pam.c

Closes #12.

### CODE REVIEW

**Comment by taigrr** [comment]
Closes #12.

File: pam.c [hunk 1]
```diff
@@ -26,6 +28,15 @@
 
 static pam_handle_t *pam_handle;
 
+static void change_identity (struct passwd *pw) {
+	if (initgroups(pw->pw_name, pw->pw_gid) == -1)
+		exit(1);
```
Comment (andydotxyz) [inline pam.c:33]: Are you sure exit(1) is the right thing to do?
If this isn't being run through systemd won't it just cause the graphical login system to exit?

**Review by andydotxyz — COMMENTED** [review]
A question about exit usage.
Also the indentation fix seems strange - it went from space indented to some-space-some-tabs.
(Go uses tabs for sure, but the C files are 4-space)

File: pam.c (hunk 1 above)
Comment (taigrr) [reply pam.c]: It's a massive security risk to continue if you fail to unset the `root` group from the running user, especially if they're not supposed to have it. 

However, this WILL NOT exit the login manager, as it gets called inside of a `fork()`ed process. As such, I've updated it to the more correct `_Exit()` call instead,

Sorry about the spacing, I think I've fixed it now.

Comment (taigrr) [reply pam.c]: ....I mean now! Now spacing should be fixed.

**Review by andydotxyz — APPROVED** [review]
Sweet thanks
